import { expect, test, type Page } from '@playwright/test'

async function createMember(page: Page) {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible()
  await page.getByRole('link', { name: /Create an account/ }).click()
  await page.getByLabel('First name').fill('Alex')
  await page.getByLabel('Last name').fill('Sample')
  await page.getByLabel('Date of birth').fill('2000-06-15')
  await page.getByLabel('Email address').fill('alex@example.com')
  await page.getByLabel('Phone number').fill('(512) 555-0123')
  await page.getByLabel('Street address').fill('123 Sample Street')
  await page.getByLabel('City').fill('San Marcos')
  await page.getByLabel('State').selectOption('TX')
  await page.getByLabel('ZIP code').fill('78666')
  await page.getByLabel('Identification type').selectOption('drivers-license')
  await page.getByLabel('Identification last four digits').fill('4821')
  await page.getByLabel('SSN last four digits').fill('0000')
  await page.getByLabel('Create password').fill('safe-password')
  await page.getByLabel('Confirm password').fill('safe-password')
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(page.getByRole('heading', { name: /What are you looking for/ })).toBeVisible()
  await page.getByRole('button', { name: /Everyday banking/ }).click()
  await page.getByRole('button', { name: /Direct deposit/ }).click()
  await page.getByLabel('Employment or student status').selectOption('Student')
  await page.getByLabel('Minimum annual income ($)').fill('40000')
  await page.getByLabel('Maximum annual income ($)').fill('20000')
  await page.getByRole('button', { name: /Continue to my recommendation/ }).click()
  await expect(page.getByText(/Enter both amounts/)).toBeVisible()
  await page.getByLabel('Minimum annual income ($)').fill('0')
  await page.getByRole('button', { name: /Continue to my recommendation/ }).click()
  await page.getByRole('button', { name: 'Back to choices' }).click()
  await expect(page.getByLabel('Employment or student status')).toHaveValue('Student')
  await expect(page.getByLabel('Minimum annual income ($)')).toHaveValue('0')
  await expect(page.getByLabel('Maximum annual income ($)')).toHaveValue('20000')
  await page.getByRole('button', { name: /Continue to my recommendation/ }).click()
  await expect(page.getByRole('heading', { name: /clear starting point/ })).toBeVisible()
  await expect(page.locator('.card-design-option img')).toHaveCount(3)
  expect(await page.locator('.card-design-option img').evaluateAll(images => images.every(image => (image as HTMLImageElement).naturalWidth > 0))).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('radio', { name: /Texas State University/ }).check()
  await page.getByRole('button', { name: /Review my information/ }).click()
  await expect(page.getByText('Texas State University', { exact: true })).toBeVisible()
  await expect(page.getByText('Student', { exact: true })).toBeVisible()
  await expect(page.getByText('$0.00 – $20,000.00', { exact: true })).toBeVisible()
  await expect(page.getByText('•••• 0000')).toBeVisible()
  const consent = page.getByRole('checkbox')
  await consent.nth(0).check()
  await consent.nth(1).check()
  await page.getByRole('button', { name: /Continue to review/ }).click()
  await expect(page.getByRole('heading', { name: /Reviewing your UFCU setup/ })).toBeVisible()
  await expect(page.getByRole('heading', { name: /Congratulations, Alex/ })).toBeVisible({ timeout: 10000 })
  await page.getByRole('button', { name: /Continue with card setup/ }).click()
  await expect(page.getByRole('heading', { name: 'Cards & Wallet' })).toBeVisible()
  await expect(page.getByAltText('Your selected UFCU debit card design')).toHaveAttribute('src', '/images/cards/texas-state.png')
  await page.getByRole('button', { name: 'Activate card' }).click()
  await page.getByRole('button', { name: /Continue to dashboard/ }).click()
  await expect(page).toHaveURL(/\/dashboard$/)
}

test('starts at login and completes the member setup journey', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Good morning' })).toHaveCount(0)
  await expect(page.getByText('Goals', { exact: true })).toHaveCount(0)

  await createMember(page)
  await expect(page.getByRole('heading', { name: 'Good morning, Alex.' })).toBeVisible()
  await expect(page.getByText('Goals', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('navigation', { name: 'Member navigation' }).getByRole('link', { name: 'Learn AI', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /Direct Deposit/ })).toBeVisible()
})

test('Learn AI provides security guidance and Profile shows member information', async ({ page }) => {
  await createMember(page)
  await page.getByRole('navigation', { name: 'Member navigation' }).getByRole('link', { name: 'Learn AI', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Learn AI' })).toBeVisible()
  await page.getByRole('button', { name: /Phishing messages/ }).click()
  await expect(page.getByText(/Watch for urgent language/)).toBeVisible()

  await page.getByRole('link', { name: /Profile/ }).first().click()
  await expect(page.getByRole('heading', { name: 'Your profile' })).toBeVisible()
  await expect(page.getByText('Date of birth')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Alex Sample', exact: true })).toBeVisible()
})

test('Direct Deposit uses employer selection, secure handoff, paycheck details, and confirmation', async ({ page }) => {
  await createMember(page)
  await page.getByRole('button', { name: /Direct Deposit/ }).click()
  await expect(page.getByRole('heading', { name: 'Direct Deposit' })).toBeVisible()
  await page.getByLabel('Organization or employer').selectOption({ label: 'Texas State University' })
  await expect(page.getByLabel('Your name')).toHaveValue('Alex Sample')
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(page.getByText(/secure employer portal/)).toBeVisible()
  await expect(page.getByText(/does not collect or store your employer username or password/)).toBeVisible()
  await page.getByRole('button', { name: /Continue to secure employer portal/ }).click()
  await expect(page.getByText('Your paycheck is ready to organize')).toBeVisible()
  await expect(page.getByText('$1,842.50')).toBeVisible()
  await page.getByRole('button', { name: /Review setup/ }).click()
  await page.getByRole('button', { name: /Submit setup/ }).click()
  await expect(page.getByText('Direct deposit setup submitted.')).toBeVisible()
})

test('dashboard interactions expose notifications, Move Money, and masked account details', async ({ page }) => {
  await createMember(page)
  await page.getByRole('button', { name: 'Notifications' }).click()
  await expect(page.getByRole('heading', { name: 'Notifications' })).toBeVisible()
  await page.getByRole('button', { name: /Paycheck incoming/ }).click()
  await page.getByRole('button', { name: 'Mark all read' }).click()

  await page.getByRole('link', { name: /Move Money/ }).click()
  await expect(page.getByRole('dialog', { name: /What would you like to do/ })).toBeVisible()
  await page.getByRole('button', { name: /Transfer/ }).click()
  await expect(page.getByRole('heading', { name: 'Move Money' })).toBeVisible()

  await page.getByRole('link', { name: /Overview/ }).click()
  await page.getByRole('link', { name: /CHECKING/ }).click()
  await expect(page.getByRole('heading', { name: 'Everyday Checking' })).toBeVisible()
  await expect(page.getByText('•••• 4821')).toBeVisible()
  await page.getByRole('button', { name: /Reveal account details/ }).click()
  await expect(page.getByText('1234564821')).toBeVisible()
})

test('mobile member dashboard has no horizontal overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await createMember(page)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await expect(page.getByRole('navigation', { name: 'Member navigation' })).toBeVisible()
  await expect(page.getByText('Goals', { exact: true })).toHaveCount(0)
})


test('ID image preview validates files and can be replaced or removed', async ({ page }) => {
  await page.goto('/signup')
  const upload = page.locator('#identity-image')
  await upload.setInputFiles({ name: 'invalid.txt', mimeType: 'text/plain', buffer: Buffer.from('invalid') })
  await expect(page.getByRole('alert')).toHaveText('Choose a JPG, PNG, or WebP image.')
  await upload.setInputFiles({ name: 'large.png', mimeType: 'image/png', buffer: Buffer.alloc(5 * 1024 * 1024 + 1) })
  await expect(page.getByRole('alert')).toHaveText('Choose an image smaller than 5 MB.')
  await upload.setInputFiles('public/images/cards/classic.png')
  await expect(page.getByAltText('Selected identification preview')).toBeVisible()
  await expect(page.getByRole('status')).toContainText('classic.png')
  await upload.setInputFiles('public/images/cards/texas.png')
  await expect(page.getByRole('status')).toContainText('texas.png')
  await page.getByRole('button', { name: 'Remove image' }).click()
  await expect(page.getByAltText('Selected identification preview')).toHaveCount(0)
})


test('sign-in opens the dashboard directly, including after sign-out', async ({ page }) => {
  await page.goto('/preferences')
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible()
  for (let attempt = 0; attempt < 2; attempt++) {
    await page.getByLabel('Email or username').fill('member@example.com')
    await page.getByLabel('Password', { exact: true }).fill('demo-password')
    await page.getByRole('button', { name: 'Sign in', exact: true }).click()
    await expect(page).toHaveURL(/\/dashboard$/)
    await expect(page.getByRole('heading', { name: 'Good morning, Ayush.' })).toBeVisible()
    if (attempt === 0) await page.getByRole('button', { name: 'Sign out' }).click()
  }
})

test('merchant rows and map pins open their own offer details', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByLabel('Email or username').fill('member@example.com')
  await page.getByLabel('Password', { exact: true }).fill('demo-password')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('main').getByRole('link', { name: 'Nearby Offers' }).click()
  await page.getByRole('button', { name: 'Allow once' }).click()
  for (const [merchant, headline] of [['H-E-B', '$5 back on groceries'], ['Target', '10% back on your next shop'], ['Local Coffee', '$2 off your coffee break']]) {
    const trigger = page.getByRole('button', { name: `View ${merchant} offer`, exact: true })
    await trigger.click()
    const dialog = page.getByRole('dialog', { name: `${merchant} offer` })
    await expect(dialog).toBeVisible()
    await expect(dialog.getByText(headline, { exact: true })).toBeVisible()
    await expect(dialog.getByText('Demo offer · Not redeemable')).toBeVisible()
    expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    await page.keyboard.press('Escape')
    await expect(dialog).toHaveCount(0)
    await expect(trigger).toBeFocused()
    await page.getByRole('button', { name: `View ${merchant} offer on map`, exact: true }).click()
    await expect(dialog).toBeVisible()
    await dialog.getByRole('button', { name: 'Back to offers' }).click()
    await expect(dialog).toHaveCount(0)
  }
})
