import { expect, test, type Page } from '@playwright/test'

async function enterApplicant(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Let’s get started' }).click()
  await page.getByLabel('First name', { exact: true }).fill('Alex')
  await page.getByLabel('Last name', { exact: true }).fill('Sample')
  await page.getByLabel('Date of birth', { exact: true }).fill('1995-06-15')
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByLabel('Email address').fill('alex@example.com')
  await page.getByLabel('Mobile phone number').fill('(512) 555-0123')
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByLabel('Street address', { exact: true }).fill('123 Sample Street')
  await page.getByLabel('City', { exact: true }).fill('Austin')
  await page.getByLabel('State', { exact: true }).selectOption('TX')
  await page.getByLabel('ZIP code').fill('78701')
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
}

async function expectNoOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
}

test('complete desktop journey retains data, validates, rotates tips, and stays local', async ({ page }, testInfo) => {
  const runtimeErrors: string[] = []
  const externalRequests: string[] = []
  page.on('pageerror', error => runtimeErrors.push(error.message))
  page.on('request', request => {
    if (!request.url().startsWith('http://127.0.0.1:5173') && !request.url().startsWith('data:')) externalRequests.push(request.url())
  })
  await page.goto('/')
  await page.screenshot({ path: testInfo.outputPath('desktop-welcome.png'), fullPage: true })
  await page.getByRole('button', { name: 'Let’s get started' }).click()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(page.getByText('Enter your first name.')).toBeVisible()
  await expect(page.getByLabel('First name', { exact: true })).toBeFocused()

  await enterApplicant(page)
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(page.getByText('Select at least one account to continue.')).toBeVisible()
  await page.getByRole('button', { name: 'Help me choose' }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Help me choose' })).toBeFocused()
  await page.getByRole('button', { name: 'Learn more about Free Checking', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('product-detail placeholder')
  await page.getByRole('button', { name: 'Back to accounts' }).click()
  await page.getByRole('checkbox', { name: /Select account\s*:\s*Free Checking/ }).check()
  await page.getByRole('checkbox', { name: /Select account\s*:\s*Simply U Checking/ }).check()
  await page.screenshot({ path: testInfo.outputPath('desktop-accounts.png'), fullPage: true })
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(page.getByText('Choose a funding method.')).toBeVisible()
  await page.getByRole('radio', { name: /Connect another bank/ }).check()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(page.getByText('Choose a demo bank.')).toBeVisible()
  await page.getByLabel('Demo bank', { exact: true }).selectOption('Demo Community Bank')
  await page.getByLabel('Total deposit amount ($)').fill('50.00')
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: /Selected\s*:\s*Free Checking/ })).toBeChecked()
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(page.getByLabel('Total deposit amount ($)')).toHaveValue('50.00')
  await expect(page.getByLabel('Demo bank', { exact: true })).toHaveValue('Demo Community Bank')
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await expect(page.getByText('Alex Sample', { exact: true })).toBeVisible()
  await expect(page.getByText('$50.00 total simulated deposit')).toBeVisible()
  await page.getByRole('button', { name: 'Submit Application' }).click()
  await expect(page.getByText('Accept the sample disclosures to continue.')).toBeVisible()
  await page.getByLabel('I have read and accept').check()
  await page.getByRole('button', { name: 'Submit Application' }).click()
  await expect(page.getByText('Confirm your consent to submit this demo application.')).toBeVisible()
  await page.getByLabel('I consent to submitting').check()
  await page.clock.install()
  await page.getByRole('button', { name: 'Submit Application' }).click()
  await expect(page.getByRole('heading', { name: 'Creating your UFCU account...' })).toBeVisible()
  await expect(page.getByText('Never share one-time verification codes with someone who contacts you.')).toBeVisible()
  await page.clock.fastForward(2100)
  await expect(page.getByText('Be cautious of urgent requests to move money to a “safe” account.')).toBeVisible()
  await page.clock.fastForward(2000)
  await expect(page.getByText('Never share your banking password or PIN over text or email.')).toBeVisible()
  await page.clock.fastForward(2000)
  await expect(page.getByRole('heading', { name: 'Account Created Successfully' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('desktop-complete.png'), fullPage: true })
  await page.goBack()
  await expect(page).toHaveURL(/\/apply\/complete$/)
  await page.getByRole('button', { name: 'Continue', exact: true }).click()
  await page.getByRole('button', { name: 'Let’s get started' }).click()
  await expect(page.getByLabel('First name', { exact: true })).toHaveValue('')
  expect(await page.evaluate(() => ({ local: localStorage.length, session: sessionStorage.length }))).toEqual({ local: 0, session: 0 })
  expect(runtimeErrors).toEqual([])
  expect(externalRequests).toEqual([])
})

for (const method of ['manual', 'card'] as const) {
  test(`mobile flow handles ${method} funding and review edits`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width: 390, height: 844 })
    await enterApplicant(page)
    await expectNoOverflow(page)
    await page.getByRole('checkbox', { name: /Select account\s*:\s*Plus Checking/ }).check()
    await page.screenshot({ path: testInfo.outputPath('mobile-accounts.png'), fullPage: true })
    await page.getByRole('button', { name: 'Continue', exact: true }).click()
    await page.getByRole('radio', { name: method === 'manual' ? /Enter bank information manually/ : /Fund with debit\/credit card/ }).check()
    await expect(page.getByLabel(method === 'manual' ? 'Sample routing number' : 'Sample card number')).toHaveAttribute('readonly', '')
    await page.getByLabel('Total deposit amount ($)').fill('-5')
    await page.getByRole('button', { name: 'Continue', exact: true }).click()
    await expect(page.getByText('Enter an amount from $0.01')).toBeVisible()
    await page.getByLabel('Total deposit amount ($)').fill('35')
    await expectNoOverflow(page)
    await page.screenshot({ path: testInfo.outputPath('mobile-funding.png'), fullPage: true })
    await page.getByRole('button', { name: 'Continue', exact: true }).click()
    await page.getByLabel('I have read and accept').check()
    await page.getByLabel('I consent to submitting').check()
    await page.getByRole('link', { name: 'Edit contact information', exact: true }).click()
    await expect(page.getByLabel('Email address')).toHaveValue('alex@example.com')
    await page.getByLabel('Email address').fill('updated@example.com')
    for (let step = 0; step < 4; step++) await page.getByRole('button', { name: 'Continue', exact: true }).click()
    await expect(page.getByText('updated@example.com', { exact: true })).toBeVisible()
    await expect(page.getByLabel('I have read and accept')).not.toBeChecked()
    await expect(page.getByLabel('I consent to submitting')).not.toBeChecked()
    await expectNoOverflow(page)
    await page.getByLabel('I have read and accept').check()
    await page.getByLabel('I consent to submitting').check()
    await page.clock.install()
    await page.getByRole('button', { name: 'Submit Application' }).click()
    await expect(page.getByRole('heading', { name: 'Creating your UFCU account...' })).toBeVisible()
    await page.clock.fastForward(6100)
    await expect(page.getByRole('heading', { name: 'Account Created Successfully' })).toBeVisible()
    await expectNoOverflow(page)
  })
}

test('refresh and direct links cannot bypass required steps', async ({ page }) => {
  await page.goto('/apply/complete')
  await expect(page).toHaveURL(/\/apply\/personal$/)
  await enterApplicant(page)
  await page.reload()
  await expect(page).toHaveURL(/\/apply\/personal$/)
  await expect(page.getByLabel('First name', { exact: true })).toHaveValue('')
})
